ziggo0 - 'NoneType' object has no attribute 'iter'
2015-11-19 15:13:06,927 (7f31917fa700) :  DEBUG (__init__:489) - AniDB Genres (Weight): []*
2015-11-19 15:13:06,928 (7f31917fa700) :  CRITICAL (agentkit:1067) - Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://449?lang=en' (most recent call last):
  File "bundles-release/Framework.bundle-dist-ninja/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1065, in _update
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 679, in update
    def update(self, metadata, media, lang, force ): self.Update(metadata, media, lang, force,  False )
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 489, in Update
    if log == 'Plex themes missing':  string = WEB_LINK % ("https://plexapp.zendesk.com/hc/en-us/articles/201572843","Restrictions") + "<br />\n"
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 527, in anidbCollectionMapping
    for element in AniDB_collection_tree.iter("anime"):
AttributeError: 'NoneType' object has no attribute 'iter'