episode title fix + AnimeLists crash fix
2018-06-06 18:49:04,881 (1890) :  INFO (logkit:16) - id: tvdb-261862, title: None, lang: en, force: True, movie: False
2018-06-06 18:49:04,882 (1890) :  INFO (logkit:16) - -------------------------------------------------------------------------------------------------------------------------------------------------------------
2018-06-06 18:49:04,882 (1890) :  INFO (logkit:16) - AnimeLists.GetMetadata() - tvdb_numbering: True
2018-06-06 18:49:04,891 (1890) :  INFO (logkit:16) - [+] AniDBid:  8883, TVDBid: 261862, defaulttvdbseason:  1, offset:   0, name: Chuunibyou demo Koi ga Shitai!
2018-06-06 18:49:04,891 (1890) :  INFO (logkit:16) -     - season: [ 0],           [ 0], range:      [000-000], offset:   0, text: 1-14
2018-06-06 18:49:04,892 (1890) :  CRITICAL (core:574) - Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://tvdb-261862?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-4898d7d96\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\admin\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 130, in update
    def update (self, metadata, media, lang, force ):  Update (metadata, media, lang, force,  False)
  File "C:\Users\admin\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 107, in Update
    dict_AnimeLists, AniDBid, TVDBid, TMDbid, IMDbid, mappingList =  AnimeLists.GetMetadata(media, movie, error_log, metadata.id,                   AniDBMovieSets) #, AniDBTVDBMap
  File "C:\Users\admin\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\AnimeLists.py", line 97, in GetMetadata
    Log.Warn("'anime-list TVDBid missing.htm' log added as tvdb serie id missing in mapping file: '%s'" % TVDBid)
AttributeError: 'NoneType' object has no attribute 'strip'

Ep title was last source regardless if ep title present or not
Plex used date as title if none

Added AniDB rating for eps by default for old series