TypeError: int() argument must be a string or a number, not 'NoneType'
https://github.com/ZeroQI/Hama.bundle/issues/580

File "/media/disk3/plexdata/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/AnimeLists.py", line 182, in GetMetadata
    Log.Info('"anime-list TVDBid missing.htm" log added as tvdb serie id missing in mapping file: "{}"'.format(TVDBid))
TypeError: int() argument must be a string or a number, not 'NoneType'