Update call crashes when files are unavailable
Happens when files have been moved or are on currently disconnected remote storage.
--------------------------------------------------
  File "...\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\Local.py", line 26, in GetMetadata
    subfolder_count     = len([file for file in os.listdir(series_root_folder) if os.path.isdir(os.path.join(series_root_folder, file))])
  File "...\Framework.bundle\Contents\Resources\Versions\2\Python\subsystem\ospathfix.py", line 111, in os_listdir
    return os._listdir(longpathify(uni(path)))
WindowsError: [Error 3] The system cannot find the path specified
--------------------------------------------------