Update __init__.py
https://github.com/ZeroQI/Hama.bundle/issues/110
needed to import io and use io.open, otherwise it doesn't know "open" that works as is in the scanner...

2017-01-10 10:35:02,138 - com.plexapp.agents.hama (-beee4c0) : INFO (__init__/Update:649) - --- Update Begin -------------------------------------------------------------------------------------------
2017-01-10 10:35:02,139 - com.plexapp.agents.hama (-beee4c0) : INFO (__init__/Update:649) - metadata source: 'anidb', id: '11985', Title: 'None', lang: 'en', (True)
2017-01-10 10:35:02,139 - com.plexapp.agents.hama (-beee4c0) : INFO (__init__/anidbTvdbMapping:746) - Finding media path
2017-01-10 10:35:02,140 - com.plexapp.agents.hama (-beee4c0) : INFO (__init__/anidbTvdbMapping:777) - dir: '/volume1/downloads/_Plex_Current issues/Urara Meirochou [anidb-11985]'
2017-01-10 10:35:02,140 - com.plexapp.agents.hama (-beee4c0) : INFO (__init__/anidbTvdbMapping:783) - No local custom mapping in dir: '/volume1/downloads/_Plex_Current issues/Urara Meirochou [anidb-11985]'
2017-01-10 10:35:02,141 - com.plexapp.agents.hama (-beee4c0) : INFO (__init__/anidbTvdbMapping:777) - Loading local custom mapping - url: '/volume1/downloads/_Plex_Current issues/anime-list-custom.xml'
2017-01-10 10:35:02,143 - com.plexapp.agents.hama (-beee4c0) : CRITICAL (agentkit/_update:1067) - Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://anidb-11985?lang=en' (most recent call last):
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-b38628e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1065, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 1023, in update
    def update(self, metadata, media, lang, force ): self.Update(metadata, media, lang, force,  False )
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 733, in Update
    elif not movie and (len(media.seasons)>2 or max(map(int, media.seasons.keys()))>1):  keys = ["tvdbid: %s"  % (WEB_LINK % (TVDB_SERIE_URL  % tvdbid,  tvdbid) )]
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 777, in anidbTvdbMapping
    elif tvdbid in ("", "unknown"):  error_log ['anime-list tvdbid missing'].append("anidbid: %s | Title: '%s' | Has no matching tvdbid ('%s') in mapping file | " % (anidb_id, name, tvdbid) + WEB_LINK % (ANIDB_TVDB_MAPPING_FEEDBACK % ("aid:%s &#39;%s&#39; tvdbid:" % (anidb_id, name), String.StripTags( XML.StringFromElement(anime, encoding='utf8')) ), "Submit bug report"))
NameError: global name 'open' is not defined