custom mapping file code broke Movie library
https://github.com/ZeroQI/Hama.bundle/issues/107

2017-01-02 19:17:21,417 - com.plexapp.agents.hama (13668) : INFO (logkit/Info:16) - --- Update Begin -------------------------------------------------------------------------------------------
2017-01-02 19:17:21,417 - com.plexapp.agents.hama (13668) : INFO (logkit/Info:16) - metadata source: 'anidb', id: '6655', Title: 'Macross Frontier: The False Diva', lang: 'en', (True)
2017-01-02 19:17:21,417 - com.plexapp.agents.hama (13668) : INFO (logkit/Info:16) - Finding media path
2017-01-02 19:17:21,418 - com.plexapp.agents.hama (13668) : CRITICAL (core/log_exception:574) - Exception in the update function of agent named 'HamaMovies', called with guid 'com.plexapp.agents.hama://anidb-6655?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-1bef33a\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1065, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\Kingsley\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 1002, in update
    def update(self, metadata, media, lang, force ): self.Update(metadata, media, lang, force,  True )
  File "C:\Users\Kingsley\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 725, in Update
    elif not movie and (len(media.seasons)>2 or max(map(int, media.seasons.keys()))>1):  keys = ["tvdbid: %s"  % (WEB_LINK % (TVDB_SERIE_URL  % tvdbid,  tvdbid) )]
  File "C:\Users\Kingsley\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 738, in anidbTvdbMapping
    for s in media.seasons:  #get first file path
AttributeError: 'MediaTree' object has no attribute 'seasons'