AttributeError: 'int' object has no attribute 'startswith'
https://github.com/ZeroQI/Hama.bundle/issues/267 - Missing brackets around the 'os.path.join' for required poster tupple