fix crash bug
Checking Plex Medis Server / Logs / PMS Plugins Logs / com.plexapp.agents.hama.log
SyntaxError: Line 133: "_nsre" is an invalid variable name because it starts with "_"