TypeError: argument of type 'int' is not iterable
https://github.com/ZeroQI/Hama.bundle/issues/267 - Fix return of "TheMovieDb.GetMetadata()" -> TSDbid/TMDbid to be a string. As causes crash in "FanartTV.py"