Minor changed to reporting
In GetImagesFromTheTVDB: Data.Save(filename, poster). if folder not there, trouble
TypeError: not enough arguments for format string. serie had no posters... coincidence?