fix crash tvdbid not in mapping file
CRITICAL (agentkit:1057) - Exception in the update function of agent named 'HamaTV', called with guid 'com.plexapp.agents.hama://anidb-262?lang=en' (most recent call last):
File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1055, in _update
File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/init.py", line 677, in update
def update(self, metadata, media, lang, force ): self.Update(metadata, media, lang, force, False )
File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/init.py", line 488, in Update
if log == 'Plex themes missing': string = WEB_LINK % ("https://plexapp.zendesk.com/hc/en-us/articles/201572843","Restrictions") + "
\n"
Thanks Worldz for great feedback

NameError: global name 'url' is not defined

url variable used but not defined which crash the agent when tvdb id not in mapping file. replaced url variable with "TVDB_HTTP_API_URL % tvdbid)" [solved]. Excellent, that was the agent bug i was looking for but only triggers for rare series not in xml mapping file