Added logging for HamaMovies
IOError: [Errno 2] No such file or directory: u'\\\\?\\C:\\Users\\deadma3ay75\\AppData\\Local\\Plex Media Server\\Plug-in Support\\Data\\com.plexapp.agents.hama\\DataItems\\_Logs\\._Plex themes missing.htm'